[package]
name = "cloudi-gen"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bat = "0.24.0"
clap = { version = "4.4.18", features = ["derive"] }
derive_builder = "0.13.0"
miette = { version = "5.10.0", features = ["fancy"] }
serde = { version = "1.0.195", features = ["derive"] }
serde_yaml = "0.9.31"
