[package]
name = "cloudi-gen"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bat = "0.24.0"
clap = { version = "4.5.3", features = ["derive"] }
derive_builder = "0.20.0"
miette = { version = "7.2.0", features = ["fancy"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_yaml = "0.9.32"
